### ISSUE TITLE
Design the Accessibility statement page for the platform

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#103]
## Accessibility statement page for the platform
You're to design and create content for the Accessibility statement page of the website.
The involves the 
* Lo-fi
* Hi-fi 
* Mobile view

**Comment by TaiwoOdeyemii** [comment]
This page shows our users that we care about them and that our platform is usable for as many people as possible. It provides our users with information about the accessibility of the content on our platform and also demonstrates our commitment to social responsibility.

**Comment by TaiwoOdeyemii** [comment]
I'm done with this task.

Here is the lo-fi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1679%3A7652

This is the hi-fi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1713%3A7895

And the mobile view of the accessibility page
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2661%3A7380
