### ISSUE TITLE
Design the page for debtor to upload receipts to support their contention

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#104]
# Verifiable document upload flow

Design the page for a debtor to upload receipts that prove or verify their payment in support to the contention they're making. You're to create the lo-fi, hi-fi and Mobile views for these pages; 

* Verifiable document upload page

* Document Uploading page

* Upload success page

* Upload failed page

**Comment by Edo-sketch** [comment]
The following are the issues I was assigned to resolve and their respective pages:  

* https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=1388%3A4950
*  https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=2566%3A7712
* https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=2566%3A7915
* https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=2566%3A8089

**Comment by Edo-sketch** [comment]
The following are the issues I was assigned to resolve, their respective pages and different screens:

### * Verifiable Document Upload Pages

Lo-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2651%3A7375

Hi-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1388%3A4950

Mobile Screen:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2620%3A7198

### * Document Uploading Pages
Lo-Fi: 
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2651%3A7788

Hi-Fi: 
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2566%3A7712

Mobile Screen:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2620%3A7347

### * Upload Success Page

Lo-Fi: 
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2651%3A7504

Hi-Fi: 
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2566%3A7915

Mobile:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2620%3A7543 

* ### Upload Failed Pages

Lo-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2651%3A7646

Hi-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2566%3A8089

Mobile:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2620%3A7719
