### ISSUE TITLE
Design the Sign up screen

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#110]
This includes screens for;
- Lo-Fi
- Hi-Fi
- Mobile view

**Comment by drvicky007** [comment]
I am done with the task. I designed for the error pages as well.

Lo-fi for sign up page: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2406%3A8294

Lo-fi for sign up error page: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2879%3A7986

Hi-fi for sign up page: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2542%3A9071

Hi-fi for sign up error page: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2306%3A8393

Mobile View for sign up page: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2542%3A8678

Mobile View for sign up error page: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2542%3A8972
