### ISSUE TITLE
Design the page for the terms and conditions 

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#111]

**Comment by drvicky007** [comment]
I am done with the task, below is the link to the screens:

Lo-fi: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2542%3A8526 

Hi-fi: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1514%3A5705

Mobile View: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2542%3A8939
