### ISSUE TITLE
Design the privacy policy page for my debtors

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#116]

**Comment by A-sammyyy** [comment]
Below are the links to the 'Privacy Policy' page I was assigned.
Low Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2521%3A8477
High Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1440%3A5027
Mobile Screen
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2644%3A7389
