### ISSUE TITLE
Design the "About Us" screen for My debtors

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#117]

**Comment by A-sammyyy** [comment]
Below are the links to the 'About Us' page I was assigned.
Low Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=647%3A224
High Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2567%3A7347
Mobile Screen
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2619%3A7370
