### ISSUE TITLE
Design the help and support screen.

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#118]

**Comment by Jeremiahnosakhare** [comment]
This screen provides authenticated users maximum support on how to use the platform and resolve technical issues that may arise with the use of the platform. The help and support screen presents users with a repository of resources and multimedia with further options for getting help from a community of users. Users also have access to messaging centre and a live-in call centre where they can get an immediate resolution to any issues.

**Comment by Jeremiahnosakhare** [comment]
Three different designs were created for the help and support screen. Here are the Figma links to the screens. 

- Lo-fi  https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2982%3A7958

- Hi-fi https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2628%3A7462

- Mobile view https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1621%3A7772
