### ISSUE TITLE
Design FAQ of the website

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#14]
### Frequently Asked Questions
* Design the FAQ page layout
* Add content

**Comment by MillySpiff** [comment]
I have completed this task 

Here is the Lo-fi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1309%3A5219 

The Hi-fi
 https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1538%3A5711

And the mobile view
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2563%3A8613
