### ISSUE TITLE
Design the page for Debtor's detail

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#15]
## Debtor's detail

**Comment by MillySpiff** [comment]
I have completed this task

Here is the lo-fi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=737%3A1223

The Hi-Fi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1290%3A6559

Mobile view
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1581%3A6642
