### ISSUE TITLE
Design Notification page of the website 

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#16]
### Notif Page

**Comment by MhizTemmie** [comment]
On it

**Comment by MhizTemmie** [comment]
i will be updating the logo tonight

**Comment by MhizTemmie** [comment]
I'm done with it

**Comment by MhizTemmie** [comment]
This is the link to the Lo fi   [https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=417%3A2](url)

**Comment by MhizTemmie** [comment]
This is the link to the Hi fi   [https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=866%3A1049](url)

**Comment by MhizTemmie** [comment]
This is the link to the Hi-fi https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1447%3A5110

**Comment by MhizTemmie** [comment]
This is the link to the Lo-fi  https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=792%3A981

**Comment by MhizTemmie** [comment]
This is the link to the mobile view   https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2563%3A8725
