### ISSUE TITLE
Design Login page of website

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#17]
## Login Page

**Comment by drvicky007** [comment]
I'm done with the design for the login page both for web and mobile app.

**Comment by Jaycarlx** [comment]
Nice one. Have you started the hi-fi?

**Comment by drvicky007** [comment]
Yes and I'm done with it

**Comment by drvicky007** [comment]
The design team lead just stated a correction, I'm working that

**Comment by Jaycarlx** [comment]
Okay. 
@MillySpiff will be reviewing this

**Comment by drvicky007** [comment]
I was able to fix it, so its ready now

**Comment by drvicky007** [comment]
I've fixed the design, included design for error pages and I am down with the task

Lo-fi for login page: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2406%3A8359

Lo-fi for Incorrect email & password: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2406%3A8436

Lo-fi for Incorrect Email: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2406%3A8514

Lo-fi for Incorrect Password: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2406%3A8592

Hi-fi for Login page: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1312%3A4992

Hi-fi for Incorrect email & password: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2272%3A8332

Hi-fi for Incorrect Email: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2278%3A8183

Hi-fi for Incorrect Password: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2278%3A8303

Mobile view for Login page: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2542%3A8729

Mobile view for Incorrect email & password: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2542%3A8859

Mobile view for Incorrect Email: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2542%3A8815

Mobile view for Incorrect Password: https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2542%3A8771
