### ISSUE TITLE
Design Contact-us page of website

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#18]
## Contact Us

**Comment by A-sammyyy** [comment]
On it!

**Comment by A-sammyyy** [comment]
Below are the links to the 'Contact Us' page I was assigned.
Low Fidelity (Page)
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=590%3A185
High Fidelity (Page)
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1418%3A4999
Low Fidelity (Pop-up)
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1612%3A7576
High Fidelity (Pop-up)
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1652%3A7649
Mobile
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2588%3A7411
