### ISSUE TITLE
Landing Page Design

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#3]
### Landing Page Design

**Comment by MillySpiff** [comment]
I am done with this task

Here is the lo- fi 
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=494%3A11 

This is the hi-fi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=2095%3A7775 

And the mobile view of the landing page
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=2454%3A8662
