### ISSUE TITLE
Design the verification pages for the website

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#38]
## Verification pages for the website
You're to design :
* The page for the user to verify by email
* The page where they input the email
* The page where they input the verification code sent to their email
* And the verification success and fail pages.

@MillySpiff will be reviewing this.

**Comment by Edo-sketch** [comment]
Below are the pages I was assigned to design and their respective Figma links.


* https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=2413%3A8300
* https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=2413%3A8321
* https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=2413%3A8363
* https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=2413%3A8388

**Comment by Edo-sketch** [comment]
Below are the pages I was assigned to design and their respective Figma links.

* https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=1313%3A4870
* https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=1313%3A5108
* https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=1313%3A5152
* https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=1313%3A5177

**Comment by Edo-sketch** [comment]
The following are the issues I was assigned to resolve, their respective pages and different screens:

### * Verification Page-1

Lo-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=531%3A268

Hi-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1313%3A4870

Mobile:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2563%3A8515

### * Verification Page-2

Lo-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=531%3A239

Hi-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1313%3A5108

Mobile:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2563%3A8673

### * Verification Success Page

Lo-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=531%3A28

Hi-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1313%3A5152

Mobile: 
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2563%3A8702

### * Verification Failed

Lo-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=602%3A1017

Hi-Fi:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1313%3A5177

Mobile:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2563%3A8713
