### ISSUE TITLE
Design the KYC authentication page for the website

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#39]
## KYC authentication pages for the website
Design the page for users to authenticate that they're school owners by uploading documents.
You're to also design the 
* "Uploading" screen for this page
*  "Upload- fail" for this page 
* "Upload-success" for this page

@MillySpiff will be reviewing this

**Comment by Edo-sketch** [comment]
This is not what I was assigned to do. I was assigned to design the following
* Verifiable document page
* Document uploading pop up page
* Upload success page
* Upload failed page

**Comment by Jaycarlx** [comment]
Okay, will reassign

**Comment by IniubongJ** [comment]
The respective screens have been resolved.
Below are the links to screens for KYC authentication page,  authentication upload success &  authentication upload failed pages as well.

###  KYC Authentication page
LOW-FI:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2910%3A8249
HI-FI:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1326%3A4895


###  Upload success page
LOW-FI:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2910%3A8320
HI-FI:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2671%3A7204


###  Upload failed page
LOW-FI:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2910%3A8375
HI-FI:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2671%3A7256


MOBILE SCREENS:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2574%3A7382
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2574%3A7461
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2574%3A7523
