### ISSUE TITLE
Design the dashboard

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#40]

**Comment by Izraelight** [comment]
Here is my submission for the Dashboard Design.

Low-Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=560%3A39

High-Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1275%3A1603

Mobile View
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1581%3A6387

**Comment by MillySpiff** [comment]
Add the lo fi screen too do this for all your tasks
