### ISSUE TITLE
Design  the feed screen for the school

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#41]

**Comment by Izraelight** [comment]
Here's my submission for the Feed Screen

Low-Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1011%3A1878

High-Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1287%3A3348

Mobile View
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1581%3A6626
