### ISSUE TITLE
Design page to add a new debtor

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#44]

**Comment by Izraelight** [comment]
Here's my submission for Add a New Debtor

Low-Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=565%3A193

High-Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1300%3A3725

Mobile View
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1581%3A6735
