### ISSUE TITLE
Design page with the list of schools in the locality

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#45]

**Comment by Izraelight** [comment]
Here's my submission for the List Of Schools In A Locality page.

Low-Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1011%3A963

High-Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2018%3A9080

Mobile View
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1581%3A6405
