### ISSUE TITLE
Design current debtors page 

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#46]

**Comment by Izraelight** [comment]
Here's my submission for the Current Debtors Page.

Low-Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=737%3A543

High-Fidelity
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1290%3A5783

Mobile View
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1581%3A6780
