### ISSUE TITLE
Design the page containing the debtor list for specific schools ( list that pops up after a search)

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#47]
This is the list that pops up after a school has been searched or clicked on.

**Comment by OGidos** [comment]
I am done with the Task 

This is the link to the lofi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2678%3A7678

This is the link to my Hifi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=2018%3A9080

This is the link to the mobile
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1581%3A6431
