### ISSUE TITLE
Design the error state screen 

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#48]

**Comment by OGidos** [comment]
I am done with the task  

This is the link to the Lofi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1006%3A960

This is the link to the Hifi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1545%3A7397

This is the link to the mobile 
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1581%3A6854
