### ISSUE TITLE
Design the debt summary screens

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#49]
This screen is linked to two (Pending debts and Resolved debts)

**Comment by A-sammyyy** [comment]
On it!

**Comment by A-sammyyy** [comment]
Below are the links to the 'Debt Summary' pages I was assigned.
Low Fidelity (Pending page)
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1089%3A1383

Low Fidelity (Resolved page)
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1244%3A1515

High Fidelity (Pending page)
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1440%3A5266
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2495%3A8355

High Fidelity (Resolved page)
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1440%3A5432
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2495%3A8618

Mobile (Pending page)
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2644%3A8525

Mobile (Resolved page)
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2644%3A8429
