### ISSUE TITLE
Create the email template to be sent to debtors

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#50]

**Comment by MhizTemmie** [comment]
on it

**Comment by MhizTemmie** [comment]
I'm done with it

**Comment by MhizTemmie** [comment]
this is the link to the Lo-fi page https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=866%3A1051

**Comment by MhizTemmie** [comment]
This is the link to the Hi-fi page https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1581%3A8196
