### ISSUE TITLE
Formulate User Research Plan

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#8]
## User Research Plan
 This was done by the product design track so as to better understand the persona of the user in order to build a product that would suit them

This includes the screener questions, conducting interviews for school owners and parents, etc

This task was assigned and carried out by @TaiwoOdeyemii and @Jeremiahnosakhare

**Comment by Jaycarlx** [comment]
Completed. 

**User research link:**
https://docs.google.com/document/d/1je5Hi53vbY7WuXBlzRFnQtrdK8EnCcYCXvGd6HyHaUQ/edit

**Comment by Jeremiahnosakhare** [comment]
This user research plan for the "my debtors" tech solution started with conceptualising viable features that the application should embed. The research thereafter embarked on critical reviews of respondents' opinions of the proposed solution and added features that must be included in the application. Quantitative data was gathered in a one-on-one interview with school administrators and management teams, head teachers, teachers and parents of students. The aggregated data from the interview was used in generating an empathy map. Distinguishing features from the empathy map was moderated in a brainstorming and ideation workshop after which we created a working draft of the user persona and idea prioritisation matrix. The entire process culminated the encompassing user flow.
