### ISSUE TITLE
Create FigJam Board

### ISSUE THREAD

**Issue by Jaycarlx** [zuri-training/proj_debtors-team-36#9]
## FigJam Board

Assigned to @TaiwoOdeyemii

**Comment by TaiwoOdeyemii** [comment]
The fig jam board contains the data gotten from and through the research interview. In it we have;

- the aggregate empathy map which summarizes what the interviewees “think, say, do and feel”; 
- their pain points and the possible solutions to these pain points which was gotten through ideation and brainstorming; 
- a user story that represents our ideal users; 
- a prioritization map that shows which solutions is feasible and takes little to no efforts and that which is not. And,
- a user flow that depicts how a user will interact with the platform from beginning to end.

**Comment by TaiwoOdeyemii** [comment]
We are done with this task.

Here is the link to the fig jam board 
https://www.figma.com/file/ghjmeP59FYHaQlDqRQoUrR/User-Research-(My-Debtor)-App?node-id=0%3A1

**Comment by Jeremiahnosakhare** [comment]
Our aggregated data from in-depth interviews conducted with major stakeholders was used to generate:

- A comprehensive empathy map that summarises the interviewee's thoughts, feelings and pain points.

- The tentative solutions to these pain points.

Our ideation and brainstorming workshop provides further tentative solutions to these pain points. 

The user persona and user story were used to represent our ideal users while the prioritization map highlights which solution was prioritized. The user flow expounds on the user journey when interacting with the platform.

**Comment by Jeremiahnosakhare** [comment]
Find attached the link to the board. 
https://www.figma.com/file/ghjmeP59FYHaQlDqRQoUrR/proj_debtors_team-36-User-Flow
