### ISSUE TITLE
Design the contending screen

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#93]
Design the page to contend debt the parents sent the automated email will land on with all the details of their debt and an option to contend debt.
This also includes the pop confirming the parent wants to contend and to proceed.

**Comment by IniubongJ** [comment]
Done with this

**Comment by IniubongJ** [comment]
The respective screens have been resolved.
Below are the links to screens for contending debt and pop up screen to proceed to contention.

###  Contending page screen
LOW-FI:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2910%3A7930
HI-FI:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1410%3A5698

###  Pop up to proceed to contention screen
LOW-FI:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2910%3A8151
HI-FI:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2574%3A7583

MOBILE SCREENS:
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2671%3A7413
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2671%3A7873
