### ISSUE TITLE
Design the forgot password screens

### ISSUE THREAD

**Issue by MillySpiff** [zuri-training/proj_debtors-team-36#94]
Screens include
- Forgot password?
- Email template to be sent
- Check your mail!
- Reset password

**Comment by DURDOLA** [comment]
i'm done with it

**Comment by DURDOLA** [comment]
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/proj_debtors_team-36-Figma-file?node-id=1685%3A7687

**Comment by MillySpiff** [comment]
Worked on the email template to be sent with link to reset password
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2276%3A8245 

Designed the check your mail screen

Lo-Fi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2655%3A7401 

Hi-Fi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2563%3A9023 

Mobile view
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2588%3A7519

Designed the reset password screen
Lo-Fi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2655%3A7421

Hi-Fi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2299%3A8221 

Mobile view
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2563%3A8582

**Comment by DURDOLA** [comment]
worked on forgot password screen

Lo-fi 
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1383%3A4955

Hi-fi
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=1685%3A7687

mobile view
https://www.figma.com/file/OnOlNH07Q0By2YOEDJIhi4/My-debtors-team-36?node-id=2563%3A8523
